[default]
src = 'contracts'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
verbosity = 4
gas_reports = ["*"]
fuzz_runs = 10
# See more config options https://github.com/gakonst/foundry/tree/master/config