[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/']
verbosity = 2
gas_reports = ["*"]
# See more config options https://github.com/gakonst/foundry/tree/master/config